version: '3.3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./app:/var/www/zoo/
            - ./nginx/logs:/var/log/nginx/
        links:
            - php
    php:
        image: php:7.0-fpm
        container_name: php-fpm
        volumes:
            - ./app:/var/www/zoo

